### ISSUE TITLE
404 on https://myst.tools/docs/mystjs

### ISSUE THREAD

**Issue by Carreau** [executablebooks/myst.tools#2]
### Describe the bug

On https://myst.tools/docs/mystjs, the link to react in the Architecture section is a 404:

```
Architecture

The mystjs ... [React], HTML ...
```

### Reproduce the bug

1. Got to https://myst.tools/docs/mystjs
2. Click on "React" link. 
3. 404.

### List your environment

N/A

**Comment by rowanc1** [comment]
Thank you @Carreau -- this has been picked up in the linked commit [in #214](https://github.com/executablebooks/mystjs/pull/214). Closing in this repo!
