### ISSUE TITLE
Footer links stack in weird ways on narrow screens

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/myst.tools#3]
On narrow screens, the list of links in the footer has some weird white space issues going on:

![image](https://user-images.githubusercontent.com/1839645/218260779-4fd6c31b-3f98-4f50-ae78-07b13656bed4.png)

I think that this could be improved in two ways:

1. Two different `div`s. One for the `start` part of the footer and one for the `end` part of the footer that snaps to the right. Put the logo + links in the `start` part, and the icon links in the `end` part.
2. The `start` items stack while the `end` items do not.
3. The stacked `start` items should not have white-space to their left, so they are all flush with the left side of the page
4. Finally, we might want to reduce the size of the logo a bit to make these work as one horizontal group on laptops of mid-range size. I'm on a 13" laptop which isn't that small, and the screenshot above is from that size of screen.

**Comment by rowanc1** [comment]
This has been fixed!
