### ISSUE TITLE
Local build doesn't have the same style as live website

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/myst.tools#5]
When I build the site locally, it looks different from what is on the live website:

![image](https://user-images.githubusercontent.com/1839645/218348296-53dec4d5-b848-46e4-8893-7c2c86c03e1a.png)

I followed these steps:

1. Clone the repo
2. Do `npm update -g myst-cli`
3. Run `myst start`

**Comment by rowanc1** [comment]
This is expected behaviour at the moment. We should merge the repository with https://github.com/curvenote/myst-tools-theme which is what actually has the theme/renderer, and update the development docs for the website!
