### ISSUE TITLE
Padding and line-wrap are off in landing page card footer

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/myst.tools#6]
A minor UI bug I noticed. When I shrink my screen the right padding and line wrap don't seem to be acting properly for the buttons:

![image](https://user-images.githubusercontent.com/1839645/218348521-59a7226a-2f99-4f7a-8a13-f7074e66eef7.png)

**Comment by rowanc1** [comment]
Thanks @choldgraf. Are you expecting all of the footers to be aligned? Or for the links to be constrained to a single line (e.g. with overflow ellipsis)?

**Comment by choldgraf** [comment]
Sorry for not being clearer, I just meant that for the right-most card, there is no right padding when it wraps to a second line, it touches the edge of the card. I feel like we want a little bit of whitespace there.

**Comment by rowanc1** [comment]
Oh nice, padding-right looks off on top left as well. That is a much easier fix. :)

I will tag you in the pr so you can see where this goes!!
